#!/bin/bash

cd ~/tracker-backend
rm config/credentials.yml.enc
EDITOR=echo bundle exec rails credentials:edit

cd ~/reporter-backend
rm config/credentials.yml.enc
EDITOR=echo bundle exec rails credentials:edit
