#!/bin/bash

sudo yum install -y \
  autoconf          \
  automake          \
  bison             \
  bzip2             \
  curl              \
  gcc-c++           \
  git-core          \
  libffi-devel      \
  libtool           \
  libyaml-devel     \
  make              \
  openssl-devel     \
  patch             \
  readline          \
  readline-devel    \
  sqlite-devel      \
  zlib              \
  zlib-devel


git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc

echo 'eval "$(rbenv init -)"' >> ~/.bashrc
