#!/bin/bash

sudo tee /etc/nginx/nginx.conf << 'EOF'
  include /usr/share/nginx/modules/*.conf;
  user ec2-user;
  pid /run/nginx.pid;
  error_log /var/log/nginx/error.log;
  worker_processes auto;

  events {
    worker_connections 1024;
  }

  http {
    include /etc/nginx/mime.types;
    access_log /var/log/nginx/access.log;
    server_tokens off;

    upstream app {
      server unix:/home/ec2-user/tracker-backend/puma.sock;
    }

    server {
      listen 80;
      server_name tracker-backend.truefootprint.com;
      return 301 https://$server_name$request_uri;
    }

    server {
      listen 443 ssl;
      server_name tracker-backend.truefootprint.com;

      root /home/ec2-user/tracker-backend/public;
      try_files $uri/index.html $uri @app;
      error_page 500 502 503 504 /500.html;
      client_max_body_size 100m;
      keepalive_timeout 10;

      ssl on;
      ssl_certificate /etc/letsencrypt/live/tracker-backend.truefootprint.com/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/tracker-backend.truefootprint.com/privkey.pem;

      gzip on;
      gzip_types application/json;

      location @app {
        proxy_pass http://app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
      }
    }
  }
EOF

sudo systemctl enable nginx
sudo systemctl start nginx
