#!/bin/bash

sudo tee /etc/systemd/system/tracker-backend.service << EOF
  [Unit]
  Description=Puma HTTP Server
  After=network.target

  [Service]
  Type=simple
  User=ec2-user
  WorkingDirectory=/home/ec2-user/tracker-backend
  Environment=RAILS_ENV=production
  ExecStart=/home/ec2-user/.rbenv/shims/bundle exec /home/ec2-user/.rbenv/shims/puma -b unix://puma.sock
  Restart=always

  [Install]
  WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable tracker-backend.service
sudo systemctl start tracker-backend.service

sudo tee /etc/systemd/system/field-backend.service << EOF
  [Unit]
  Description=Puma HTTP Server
  After=network.target

  [Service]
  Type=simple
  User=ec2-user
  WorkingDirectory=/home/ec2-user/field-backend
  Environment=RAILS_ENV=production
  ExecStart=/home/ec2-user/.rbenv/shims/bundle exec /home/ec2-user/.rbenv/shims/puma -b unix://puma.sock
  Restart=always

  [Install]
  WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable field-backend.service
sudo systemctl start field-backend.service
