#!/bin/bash

cat | sudo tee /etc/systemd/system/puma.service << EOF
  [Unit]
  Description=Puma HTTP Server
  After=network.target

  [Service]
  Type=simple
  User=ec2-user
  WorkingDirectory=/home/ec2-user/tracker-backend
  Environment=RAILS_ENV=production
  ExecStart=/home/ec2-user/.rbenv/shims/puma
  Restart=always

  [Install]
  WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload

sudo systemctl enable puma.service
sudo systemctl start puma.service
